### ISSUE TITLE
Throw on invalid YAML

### ISSUE THREAD

**Issue by strugee** [simbo/gulp-gray-matter#1]
I have the following YAML frontmatter in a file:

```yaml
title: "Hello, World!"
time:
	- epoch: 1487490654
	- utcoffset: "UTC-0"
author: "Alex Jordan"
categories:
	- example
```

Putting this YAML into a [YAML validator][1] returns "Error : A YAML file cannot contain tabs as indentation." It feels like gulp-gray-matter should probably throw in this situation instead of silently not adding the data in the frontmatter to the Vinyl file.

 [1]: http://codebeautify.org/yaml-validator

**Comment by strugee** [comment]
Nope, I was being dumb and forgot the `---`s, so it wasn't being parsed at all. Sorry for the noise.

**Comment by strugee** [comment]
So that particular case was my fault, but this seems to be an issue that really does exist:

```yaml
---
title: "Gender representation at RC"
time:
  epoch: 1487109679
  utcoffset: "UTC-5"
edited:
  epoch: 1487783122
  utcoffset "UTC-5"
edited:
  epoch: 1487783122
  utcoffset "UTC-5"
author: "Alex Jordan"
categories:
  - personal
  - blaggregator
---
```

is invalid YAML (notice `utcoffset "UTC-5"` is missing a `:`), but I don't get an error.
